name: ga-st-python-course

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt -r requirements-dev.txt
    - name: black
      run: |
        make black
    - name: flake8
      run: |
        make flake8
    - name: isort
      run: |
        make isort
    - name: isort
      run: |
        make isort
    - name: mypy
      run: |
        make mypy
    - name: pytest
      run: |
        make pytest

